title: LaMarche Lab
description: Cancer. Immunology. Translational Research.
theme: minima
baseurl: "/LaMarche-Lab"
plugins:
  - jekyll-sitemap

header_pages:
  - index.markdown
  - research.md
  - publications2.md
  - People.md
  - contact.md

