title: The LaMarche Lab
description: Cancer. Immunology. Translational Research.
theme: minima

# You added a CNAME → use your real domain here
url: "https://lamarchelab.com"

# Important: when using a custom domain, baseurl must be empty
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - index.markdown
  - publications2.md
  - People.md
  - contact.md
