title: LaMarche Lab
description: Cancer. Immunology. Translational Research.
theme: minima
baseurl: "/LaMarche-Lab"
plugins:
  - jekyll-sitemap

header_pages:
  - index.markdown        # Home
  - research.md     # Research
  - publications2.md # Publications
  - People.md      # Members
  - contact.md      # Contact
